version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    command: mongod --quiet
    volumes:
      - ./data:/data/db
    networks:
      - app-network

  node-app:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "7896:7896"  # Adjust if your app uses a different port
    environment:
      DATABASE_URL: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
